name: Go and node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: api/js/package-lock.json

    - run: |
        cd api/js
        npm ci

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        cd api/js
        npm run build
        cd ../..
        go build .
        go build -v ./...

    - name: Lint
      run: |
        cd api/js
        npm run check

    - name: Test
      run: |
        go test -v ./...
        cd api/js
        npm test
